### ISSUE TITLE
Associate Author with User

### ISSUE THREAD

**Issue by filby89** [winkm89/teachPress#100]
Hi, I was wondering if it is possible to associate an author with a user in wordpress (it is a step towards showing the user's publication). I can't seem to find any way to associate a user with a publication (except by logging in with the user and click "add to my list").

**Comment by winkm89** [comment]
Hi, 
It's not possible to do that automatically. But if the user has at least one publication in his list, you see his name in the bookmarks. So, then it's not necessary to log in as this user.
