### ISSUE TITLE
tp_cloud editing dropdown filter padding options and tags

### ISSUE THREAD

**Issue by abrow169** [winkm89/teachPress#107]
Hi,
I have a couple of questions and I'm not sure if they can be solved in a similar way or not. Right now, I only have 2 dropdown filters, years and authors. Right now the years dropdown is above the authors, how do I put them side by side? I've tried playing with the templates, different shortcodes for tpcloud, and trying to see if I could change something in the template php or css. 

On another note, in the "Type" I want to keep the links and the abstract, but I'm not sure of how I can get rid of the list of tags afterwards. Should I also change something in the template for that?

the page I'm editing: https://istar.jhu.edu/papers/
shortcode: 
[tpsearch]
[tpcloud link_style="direct" author_name="simple" author_separator="," show_user_filter="0" show_type_filter="0" show_tags_as="none" template="tp_template_custom"]
where tp_template_custom is a copy of template_orig_s, I haven't made modifications to it.

Thank you so much,
Alisa

**Comment by winkm89** [comment]
Hi,
Sorry for my late answer. The width of the dropdowns is given with 100% from your theme. Adding the following line to the css-file of your theme should help:
```css
select#pub_year, select#pub_author {width:auto;}
```
But: The width of the author dropdown comes also from the width of the entries in it. It seems that there are some unused entries, which were not correctly splitted from the importer. This entries should be removed over the author backend menu.

The simplest way to remove the tag line is to search the following line in the /core/shortcodes.php:

```php
'with_tags' => 1,
```
and change it to;
```php
'with_tags' => 0,
```

But I want to add a shortcode option for that, with the next version.
