### ISSUE TITLE
Author ID changes after reimport. Can that be prevented?

### ISSUE THREAD

**Issue by haicu** [winkm89/teachPress#112]
Hi the system works great, but now and than I need to delete all publications and reimport them again because the "cited by" information gets outdated. The problem is that the author ID in the reimport is different. I use the author ID to show the lists of publications, so that gets mixed up.

Is there a way to keep the author ID the same? For instance, by importing the author ID from the bibtex file instead of generating our own?
That would be great.

thanks, Han

**Comment by winkm89** [comment]
Hi Han,
There is an option under Settings-> teachPress called "Overwrite publications". This activates an option for the importer, which allows directly updating a publication if the BibTeX key is the same. Maybe this could help you.

**Comment by haicu** [comment]
Thank you. I missed that. I'll give it a try later on.
How experimental is it actually?

many greetings, Han

**Comment by winkm89** [comment]
I've updated the function a bit with v. 6.2.5 so that it's more an update instead of an overwrite. This means that information which are not given in import (like related page,..) will no longer be deleted with this option.

**Comment by haicu** [comment]
Sounds good. Thank you for letting it know.
