### ISSUE TITLE
Provide option to hide dropdown to select users

### ISSUE THREAD

**Issue by thepunitsingh** [winkm89/teachPress#115]
Please provide an option to hide or preselect on user dropdown so that either a user can be selected or the option to select users can be disabled from the page.

**Comment by winkm89** [comment]
Hi,
This options are already implemented:
`[tpcloud show_user_filter="0"] or [tpcloud user="1"] (user means the IDs of the WordPress users whose publications you want to show)`

**Comment by thepunitsingh** [comment]
Hi,

I am aware of this option, but I want to enable/hide the author selection
of the papers. Please refer to the page
https://ihciconf.org/2018/published-papers/, it will be great if I can hide
the last dropdown option.

**Comment by winkm89** [comment]
Have you tried to use [tplist] instead of [tpcloud]?

**Comment by thepunitsingh** [comment]
I just noticed the error I made in my last comment, apologies for the same. Actully I hid the user selection dropdown through css using `display:none;` and that resulted in my mistake. What I want is to hide the user selection dropdown, just like we can hide other options.

Please check the page [https://ihciconf.org/2018/published-papers/](https://ihciconf.org/2018/published-papers/) now, I've also attached a screenshot marking the same.

![image](https://user-images.githubusercontent.com/15262649/57246456-eef65780-705a-11e9-9777-ba9fc2fa1b7b.png)

I've used [tplist], but it leaves us with only a scrollable list with no dropdown selection.

**Comment by winkm89** [comment]
Should fixed with v7.0 and `[tpcloud show_user_filter="0"]`
