### ISSUE TITLE
Extra icons for URL/Files in the publication overview

### ISSUE THREAD

**Issue by sven-mayer** [winkm89/teachPress#118]
The icons in the publication overview for URL/Files are quite an old school in the first place and most just show up as the HTML icon (file with global) especially when using external links.

In the first step, I propose to add icons for specific webpages, such as youtube, vimeo, github, and similar. I think this is important since publishing datasets, code, and videos with the paper are getting more popular. 
This first part can be easily addressed by modifying the implementation of get_tp_mimetype_images in core/gerneral.php.  

As a second step, I propose, using fontawesome for icons as we would get nice new ones. However, we would be limited by the icons they provide. Thus, this I thinks needs to be discussed first (@winkm89).

**Comment by winkm89** [comment]
Hi Sven,

Thanks for the pull request! I like the idea with fontawesome. There is currently an issue with subdomains like de.wikipedia.org. But I think this could be solved. I've attached a quick comparisation between the old and the new style.

Kind regards,
Michael

![icons](https://user-images.githubusercontent.com/9537674/61400819-62c1a580-a8d1-11e9-9cd8-a9910f5a42bc.PNG)

**Comment by sven-mayer** [comment]
HI @winkm89 

I'll work on it. Both, using fontawesome and fixing the subdomain problem. Expect my pull request in the next days. Thanks.

Best
Sven
