### ISSUE TITLE
tpsearch behaviour changes in 7.0

### ISSUE THREAD

**Issue by steinbeck** [winkm89/teachPress#126]
After updating to 7.0, the [tpsearch] shortcode on my publication page shows a search field *plus*, presumably, the result of a full wildcard search (the first 20 publications in the database). The latter was not there before and messes up the functionality of this command. I would expected to just see the search box. The complete code for the page is

[tpsearch]

[tplist user="1"]

The surplus content (which I want to go away :)) is shown in the red box in the attached screenshot.

![bug](https://user-images.githubusercontent.com/107318/69493939-bf535380-0eb5-11ea-8049-2b0ec085ac14.png)

**Comment by winkm89** [comment]
Hi,

You can go back to the old behavior if you change the first shortcode to:

`[tpsearch use_as_filter="0"]`

**Comment by steinbeck** [comment]
Excellent! Thanks!
