### ISSUE TITLE
tpsearch issue

### ISSUE THREAD

**Issue by blee-ucf** [winkm89/teachPress#128]
I am having the same issue as here: https://github.com/winkm89/teachPress/issues/126#issue-527684186.  I used the recommended fix: [tpsearch use_as_filter="0"].  It takes care of the extra list of publication but if I do a search for an author by last name who has more that 20 publications, when I click the arrows to page through the search, it is not working properly.  Please help me as I will not be able to figure this out on my own.

Webpage: https://sreal.ucf.edu/publications/

**Comment by blee-ucf** [comment]
Also, it looks like I should be able to use:
template (optional) new since 6.0.0
(string) Sets the template key for the publication list. The default is "tp_template_orig_s".

But doesn't seem to work when I add:
[tpsearch use_as_filter="1" image="left" image_size="120"  author_name="simple"  style="simple" link_style="images" template="tp_template_2016"]

**Comment by winkm89** [comment]
Hi,
Thanks for the information. There was a bug in the pagination function for [tpsearch]. This should be fixed with version 7.0.3.

I've tested also you shortcode settings with the template option. I can't see an error there. This should work.
