### ISSUE TITLE
Bug: Disabling Course Module does not work

### ISSUE THREAD

**Issue by MatthiasLohr** [winkm89/teachPress#129]
Hey,

first: Thanks for the nice work!

I think I found a (minor) bug: According to https://github.com/winkm89/teachPress/wiki/FAQ#how-can-i-deactivate-parts-of-the-plugin-like-the-course-module, it should be possible to disable e.h. the course module. So I added this to the end of my `wp-config.php`:

```
define ('TEACHPRESS_COURSE_MODULE',false);
```

But in the admin menu, I still have the menu entry for the courses module. I would expect that the menu entry and any functionality regarding courses is gone after defining this in `wp-config.php`. Anyways, why not enabling/disabling parts of the plugin via the settings page?

Best regards
Matthias

**Comment by winkm89** [comment]
Hi Matthias,

I think the mistake is that editing something at the end of wp-config doesn't work! ;)
You have to set the parameter **before** this comment (or a translated version) in the wp-config.php:
`
/* That's all, stop editing! Happy blogging. */
`

**Comment by MatthiasLohr** [comment]
Oops, ok, that works. Maybe... add a little hint in the documentation?

But still the question: Why not just a checkbox in the admin interface?

**Comment by winkm89** [comment]
It's a bit faster for page loading as an option in the interface, which requires a database request. And it's not a function you change every day, so I think performance wins against comfort. :)
