### ISSUE TITLE
shortcodes not working as expected tplist/tpsearch

### ISSUE THREAD

**Issue by blee-ucf** [winkm89/teachPress#130]
Nevermind: I figured it out.

Hi Folks,

Thanks for fixing the last issue I reported.  I am still having some trouble since the major update.

I have the following shortcode on my publications page [url: https://sreal.ucf.edu/publications/]:

[tpsearch` use_as_filter="0"]

[tplist image="left" image_size="120"  author_name="simple"  style="simple" link_style="images" tag="48" type="article, book, conference, inbook, incollection, inproceedings, phdthesis, techreport, presentation, workshop" template="tp_template_2016"]

This shortcode worked when we first set-up the page.  Currently it looks like the type="..." is not limiting the list to the listed types. Our page is showing all types.  Do I need to use the exclude_types also? Is there a bug? Should it work the same as it did before?

Thank you, Barbara

**Comment by winkm89** [comment]
Hi Barbara,

Sorry for my late answer. It's seems for me, that the type parameter works as expected. Anyway, I don't recommend to use [tplist] and [tpsearch] on the same page. In you case [tpsearch] should able to provide all functions:
[tpsearch use_as_filter="1" image="left" image_size="120"  author_name="simple"  style="simple" link_style="images" tag="48" type="article, book, conference, inbook, incollection, inproceedings, phdthesis, techreport, presentation, workshop" template="tp_template_2016"]

**Comment by blee-ucf** [comment]
Hi Michael,

Thank you for the information.  I am working on making the recommended changes but with the “tp_template_2016” I am no longer seeing the year headings.

This is what I have for short code:

[tpsearch use_as_filter="1" image="left" image_size="120" author_name="simple" style="simple" link_style="images" author="5,296,166,70" type="article, book, conference, inbook, incollection, inproceedings, phdthesis, techreport, unpublished" template="tp_template_2016"]

Here is the url for the page I’m working on right now: https://sreal.ucf.edu/people/welch/dr-gregory-f-welch-publications/  We have several publications pages that will need to be changed as a result of your last major revision.

I’m not very good at website building so appreciate the help.

Best,
Barbara Lee
Assistant to Professor Gregory Welch
Office: 407.823.1021 or 407.882.1325
Please note: Florida has a very broad open records law (F.S. 119). Emails may be subject to public disclosure.
