### ISSUE TITLE
Filter of tpcloud not working with non-Latin slugs

### ISSUE THREAD

**Issue by Dollarius** [winkm89/teachPress#134]
I am working on a Japanese website where a tpcloud is used to show the list of publications, with the dropdown filters.
The page has slug `論文リスト` which should be encoded as
`%E8%AB%96%E6%96%87%E3%83%AA%E3%82%B9%E3%83%88`
while it is encoded in the dropdown SELECT of the tpcloud filters as
`%25e8%25ab%2596%25e6%2596%2587%25e3%2583%25aa%25e3%2582%25b9%25e3%2583%2588`
which means that the '%' characters are encoded again as '%25'.
For this reason, upon choosing an item in the filter the user is redirected to a "non existent page".

I temporarely solved the issue by adding a **rawurldecode** function in file 
`teachpress/core/shortcodes.php -> line 1241`
so that the old line
`'permalink' => ( get_option('permalink_structure') ) ? get_permalink() . "?" : get_permalink() . "&amp;",`
now reads
`'permalink' => ( get_option('permalink_structure') ) ? rawurldecode(get_permalink()) . "?" : rawurldecode(get_permalink()) . "&amp;",`

I would like to suggest this as a plugin fix, but I am not sure if this is the correct way of doing it.
Thank you for the great work: the plugin is awesome!

**Comment by winkm89** [comment]
Hi Dollarius,
Thanks for the report. The problem should be fixed with the next version.
