### ISSUE TITLE
Keyword search of publication list

### ISSUE THREAD

**Issue by srinivassridhar** [winkm89/teachPress#141]
Is it possible to allow a keyword search of the publication database, and return those publications that match an arbitrary keyword?

**Comment by winkm89** [comment]
Hi,
Sorry for the late reply! What you mean with "keyword search"? It's similar like the search field in [[tpsearch]](https://github.com/winkm89/teachPress/wiki/Shortcode-Reference:-%5Btpsearch%5D) or did you mean something different?

**Comment by srinivassridhar** [comment]
I believe we resolved this issue with tpsearch.
