### ISSUE TITLE
Publication pages tpsearch author=(1,2,3) only returning 1st author

### ISSUE THREAD

**Issue by blee-ucf** [winkm89/teachPress#142]
Hi Folks,
First, let me say thank you for the plugin, it makes our website look neat and tidy and has made maintaining a publications list,, even multiple publications list, easier.  We appreciate your efforts.

We are having an issue on one of our publications pages: https://sreal.ucf.edu/people/welch/dr-gregory-f-welch-publications/. 
When it initially loads the page it tells us that there are 11 pages but if we click the >> to go to the end of the list we receive an error message.  If we click the > to go page by page there are only 8 pages.  Can you please assist with this issue?  Do I need to add something to my short code to prevent this? We have multiple publications pages and this seems to be the only one we are having this issue with.

Short code for Dr. Welch's publication page:
[tpsearch use_as_filter="1" tag="49" image="left" image_size="120" author_name="simple" style="simple" link_style="images" author="5,296,166,70" type="article, book, conference, inbook, incollection, inproceedings, phdthesis, techreport, unpublished, presentation, workshop" template="tp_template_2016"]

Short code for out main publication page (https://sreal.ucf.edu/publications/)
[tpsearch use_as_filter="1" image="left" image_size="120" author_name="simple" style="simple" link_style="images" tag="48" type="article, book, conference, inbook, incollection, inproceedings, phdthesis, techreport, presentation, workshop" template="tp_template_2016"]

Since I'm asking questions.  Before the last major renovation we were using [tplist] to pull the list together.  Since we moved to using the [tpsearch] the page no longer shows the year headlines between the years worth of publications using the tp_template_2016.  Is this the way it is suppose to work? or should I be able to see the year headings?

Thank you.

**Comment by blee-ucf** [comment]
I think I may have found the issue.  It seems like author="5,70,166,296" does not work in tpsearch like it does in tplist.  Should it?

**Comment by winkm89** [comment]
Thank you for the report. It was was bug. :) Should be fixed with version 7.1.1
