### ISSUE TITLE
Punctuation lost after import publications

### ISSUE THREAD

**Issue by ThFransen84** [winkm89/teachPress#145]
Wonderful project, thank you. I noticed that a dot after an author's abbreviated second name (e.g. John R. Smith) in the BibTex file disappears after importing. Is this intentional? I know that one can insert it manually, but when (re)importing from a big file that is being changed constantly, this is not ideal. Thank you in advance!

**Comment by ThFransen84** [comment]
It seems that it remains in the underlying bibtex entry if one chooses the right format (last name, first name1 first name2), but it disappears in the reference itself.

**Comment by winkm89** [comment]
Hi,
Thanks to your report and also the infos in your email. It's a problem with the underlying bibtex parser library. Luckily I've found a silent update for this library from the original authors. Thanks to the open source license, I can reuse their new code. And the best: It's seems that this version fix that problem. So #147 should fix the problem. :)

**Comment by ThFransen84** [comment]
I think I found the solution myself: the short code `author_name="old"` does the trick. 
Is the standard setting "initials", maybe? The shortcode doc says that "last" is default, but that would mean abbreviated second names are deleted as per your example with Ludwig C. van der Vaart > van der Vaart, Ludwig , which is not the case in the current configuration. Only the dot preceded by a capital letter seems to be deleted in the default setting.

**Comment by winkm89** [comment]
Yes standard is `initials` since teachPress 6.0. I've forgot to change this in the docs. Normally `initials` works better than `old` in the some cases and is hopefully generally better with the next release. :)
