### ISSUE TITLE
Better parsing of author names in bibtex imports

### ISSUE THREAD

**Issue by winkm89** [winkm89/teachPress#15]
The form of the author names (Einstein, Albert or Albert Einstein) in bibtex imports should be automatically detected.

**Comment by winkm89** [comment]
Option for automatic detection added in teachPress 5.1

**Comment by RaulMurillo** [comment]
It seems this automatic detection is not working on the current version (9.0.0).

Here is an example bibtex:
```bibtex
@book{testBook,
title = {Sample Book},
author = {Murillo, Raul and Botella, Guillermo},
year  = {2024},
date = {2024-06-04},
keywords = {},
pubstate = {published},
tppubtype = {book}
}
```
 And the output in my Wordpress is the following:

>  Murillo, Raul; Botella, Guillermo
> 
> Sample Book Book
> 
> 2024.

I am using the following options to display the publication:
```
[tplist show_tags_as="none" author_name="simple" editor_name="simple" author_separator=";" editor_separator=","]
```

Any ideas about what is happening?
