### ISSUE TITLE
Custom label stopped working

### ISSUE THREAD

**Issue by CuypersBart** [winkm89/teachPress#157]
Hi, 

I updated to the newest Teachpress and Wordpress versions and noticed my custom labels were suddenly gone.
I re-did all the steps outlined here (including changing the code in the template), but unfortunately, this did not fix the issue.

Only the 'publication type' label remains now.
Do you know what the problem might be?

**Comment by winkm89** [comment]
Hi, 
Do you miss the custom labels only in the publication list on the webpage or also in the backend, when you add/edit a publication?

If you miss only the labels, please check if the name of the field ( starts with tp_meta_pub_* ) is really the same as the one you use in the get_entry() method. 
You can also check, if the data of the label is really available, if you add the following lines within the get_entry() method of the template and search for the custom label name in the output:

```PHP
$data = $interface->get_data();
var_dump($data['row']);
```

**Comment by CuypersBart** [comment]
Thank you so much for the debugging advice!

It was the name of the field not matching the one in get_entry() method. 

Works perfectly now.
