### ISSUE TITLE
Publication lists without HTML tables

### ISSUE THREAD

**Issue by winkm89** [winkm89/teachPress#161]
Add support for publication lists without HTML tables through templates

**Comment by jdelgadoesteban** [comment]
Really great plugin, testing it right tnow as we are migrating from a legacy Drupal. Does the plugin include any other template (for example borderless) apart from tp_template_2016?

Thanks so much!

Javier

**Comment by winkm89** [comment]
Hi Javier, 
I'm currently creating a new default template (tp_template_2021), which will be borderless and more responsive. But this is currently only available in the Github master branch and not in a release. The new template will be available with the next release (7.2).

**Comment by jdelgadoesteban** [comment]
Thanks for that @winkm89 🙏
