### ISSUE TITLE
Wordpress-DB Error showed up with  WP_DEBUG enabled - Ver. 7.1.3/4

### ISSUE THREAD

**Issue by shahab-ab** [winkm89/teachPress#163]
Hello, 
The import process works good. But Authors and Tags are empty!!

In Admin Page: wp-admin/admin.php?page=publications.php
WordPress database error: [Table 'DB4415816.tapa_teachpress_authors' doesn't exist]
SELECT DISTINCT a.name, a.author_id, count(r.author_id) AS count FROM tapa_teachpress_authors a LEFT JOIN tapa_teachpress_rel_pub_auth r ON a.author_id = r.author_id GROUP BY a.name ORDER BY a.name ASC LIMIT 0,50

in wp-admin/options-general.php?page=teachpress%2Fsettings.php&tab=db_status
tapa_teachpress_tags
WordPress database error: [Table 'DB4415816.tapa_teachpress_tags' doesn't exist]
SHOW INDEX FROM tapa_teachpress_tags

in runtime: After importing: and showing results:
1- Notice: Undefined index: author in .../wp-content/plugins/teachpress/core/class-bibtex-import.php on line 255
2- Uninitialized string offset: 0 in .../wp-content/plugins/teachpress/includes/bibtexParse/PARSEENTRIES.php on line 121
3- WordPress database error: [Table 'DB4415816.tapa_teachpress_authors' doesn't exist]
SELECT `author_id` FROM tapa_teachpress_authors WHERE `name` = 'Nandana Mihindukulasooriya'

in Authors Admin-page:
WordPress database error: [Table 'DB4415816.tapa_teachpress_authors' doesn't exist]
SELECT COUNT(a.`author_id`) AS `count` FROM tapa_teachpress_authors a ORDER BY a.sort_name ASC, a.name ASC

WordPress database error: [Table 'DB4415816.tapa_teachpress_authors' doesn't exist]
SELECT DISTINCT a.name, a.author_id, count(r.author_id) AS count FROM tapa_teachpress_authors a LEFT JOIN tapa_teachpress_rel_pub_auth r ON a.author_id = r.author_id GROUP BY a.name ORDER BY a.name ASC LIMIT 0,50

**Comment by winkm89** [comment]
Hi,
The problem is just that the database tables for authors/tags doesn't exist in your database. So, there was a problem with the plugin installation. Could you delete all exisiting teachpress database tables and reinstall the plugin? Because this could show us the real error.

**Comment by shahab-ab** [comment]
Thank you for you answer,

Exactly I have deleted the DB, and reinstalled it. There was almost 19+-1 tables, but again no authors and tags. I just downloaded this code from github and installed on my WP  and direct installation from WordPress repository as well.

**Comment by winkm89** [comment]
Mysterious...
Do you see the teachpress_tags and teachpress_authors tables in your database?
Do you know where the prefix "DB4415816" comes from?

**Comment by shahab-ab** [comment]
Exactly  🤔. No as I said these two tables are not listed. But all other tables are there.
The prefixes are actually make the problem. I checked some where in your code that might make such a prefix but I could not follow it where they are created.

**Comment by winkm89** [comment]
The table names where build in the file core/constants.php and the installation of the tables is defined in core/class-tables.php

**Comment by shahab-ab** [comment]
Hello Michael,

I just installed it on another host and from WP repository Ver7.1.4 - The 2 missing Tables were created. Though tags table is still empty for 312 entries of publications. BTW, I could not find any thing related to the prefix to the table names that is basically "tapa_" in my case, neither a way to get of this problem on my main website.! How is it possible?

**Comment by shahab-ab** [comment]
I found something: and it might help! I tried to call your tp_tables::create() and the result was as follows:

WordPress database error: [Index column size too large. The maximum column size is 767 bytes.]
CREATE TABLE tapa_teachpress_tags ( `tag_id` INT UNSIGNED AUTO_INCREMENT, `name` VARCHAR(300), PRIMARY KEY (tag_id), KEY `ind_tag_name` (`name`) ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci

WordPress database error: [Table 'DB4415816.tapa_teachpress_tags' doesn't exist]
ALTER TABLE tapa_teachpress_tags ENGINE = INNODB

WordPress database error: [Index column size too large. The maximum column size is 767 bytes.]
CREATE TABLE tapa_teachpress_authors ( `author_id` INT UNSIGNED AUTO_INCREMENT, `name` VARCHAR(500), `sort_name` VARCHAR(500), PRIMARY KEY (author_id), KEY `ind_sort_name` (`sort_name`) ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE = INNODB

WordPress database error: [Table 'DB4415816.tapa_teachpress_authors' doesn't exist]
ALTER TABLE tapa_teachpress_authors ENGINE = INNODB

**Comment by winkm89** [comment]
Now I remember!! There was an other user with the same issue [exactly one year ago](https://wordpress.org/support/topic/authors-not-populating-both-on-import-and-manual-entry/). 

**The problem is the following:**
Up to MySQL 5.6 the default index key length for InnoDB tables was 767 bytes (innodb_large_prefix = false). Since MySQL 5.7 is 3072 bytes the default (`innodb_large_prefix = true`).
The problem with **teachpress_authors** and **teachpress_tags**: Both uses an index key length of 1500 bytes (500 chars * 3 bytes). So this error can occur if MySQL or MariaDB runs with the deprecated setting `innodb_large_prefix = false`

**Comment by shahab-ab** [comment]
Thank you so much for your support.
Then I think the problem is almost solved. Should the hosting do changing the setting?
But still one remaining small issue: why the Tags table is empty?(As tested in New host with authors and tags table: Authors worked - tags are still empty).

**Comment by winkm89** [comment]
Can you add tags directly to the database or if you add a publication over the teachpress admin menus?

**Comment by shahab-ab** [comment]
Well, I can do it directly. For that I have to first extract the tags from the bin file. Since I am doing the import reqularly or whenever some new publications are released, this would not be an optimal solution though.

**Comment by shahab-ab** [comment]
Hi Michael,
The problem with missing tables: Authors & tags has by updating the DB to Ver. 5.7 been resolved. 
However I get these notices while importing:

Notice: Undefined index: author in /.../plugins/teachpress/core/class-bibtex-import.php on line 255

Notice: Uninitialized string offset: 0 in /.../plugins/teachpress/includes/bibtexParse/PARSEENTRIES.php on line 121

I thought they might be helpful.

There is no way of inserting tags in Admin page.. in terms of direct insertion in DB I am not sure if I can do it. My access is very limited. or I might not have understood your question!

**Comment by winkm89** [comment]
Is it possible, that there are just no tags in the file? I ask because in the file that you post in the other thread there are not tags. :)

You can try it with the following entry, which should add tags:
```
@article{DBLP:journals/is/OliveiraFSGML21,
  author    = {Italo Lopes Oliveira and
               Renato Fileto and
               Ren{\'{e}} Speck and
               Lu{\'{\i}}s Paulo F. Garcia and
               Diego Moussallem and
               Jens Lehmann},
  title     = {Towards holistic Entity Linking: Survey and directions},
  journal   = {Inf. Syst.},
  volume    = {95},
  pages     = {101624},
  year      = {2021},
  url       = {https://doi.org/10.1016/j.is.2020.101624},
  doi       = {10.1016/j.is.2020.101624},
  timestamp = {Sat, 07 Nov 2020 00:00:00 +0100},
  keywords = {tag1,tag2},
  biburl    = {https://dblp.org/rec/journals/is/OliveiraFSGML21.bib},
  bibsource = {dblp computer science bibliography, https://dblp.org}
} 
```

The notices are small bugs, which doesn't change the import result, but will be fixed with the next release.

**Comment by shahab-ab** [comment]
Thank you Michael for your answer. 
Ok, you're right. The import with tags was successful.! 

Best regards,
