### ISSUE TITLE
Add the ability to disable (or customize) currently hardcoded text

### ISSUE THREAD

**Issue by sibyl27** [winkm89/teachPress#164]
In some bibliographies the current hardcoded texts, such as "In: " or "Links: ", are not desirable because they are superfluous by context or styling.
For instance I need to apply the following patch each time I update teachpress:
[teachpress.txt](https://github.com/winkm89/teachPress/files/6360362/teachpress.txt)

It would be nice to have an option to disable these hardcoded texts, or to customize them (in which case, of course, i18n would not apply).

**Comment by winkm89** [comment]
Hi,
I've added two options to edit/remove this labels:

**1. Own CSS selectors**
```CSS
/* For Tags: */
.tp_pub_tags_label {}
/* For In: */
.tp_pub_additional_in {}
/* For Links (only if link_style=image) */
.tp_pub_links_label {}
```
For example: This hides the _In:_ text
```CSS
.tp_pub_additional_in {
    display: none;
}
```

**2. Own template settings**
The label names can now be defined in the template settings:
```PHP
public function get_settings() {
        return array ('name'                => 'teachPress 2021',
                      'description'         => 'A new mobile friendly 4 line style template for publication lists.',
                      'author'              => 'Michael Winkler',
                      'version'             => '1.0',
                      'button_separator'    => ' | ',
                      'menu_label_tags'     => __('Tags') . ': ',
                      'menu_label_links'    => __('Links','teachpress') . ': ',
                      'meta_label_in'       => __('In','teachpress') . ': ',
                      'citation_style'      => 'teachPress'
        );
    }
```

Both options will be available with the upcoming teachPress 7.2.

**Comment by sibyl27** [comment]
That's perfect and awesome, a big Thank You Michael !

**Comment by shahab-ab** [comment]
Hello,
I expected template 2021 to be added to version 7.1.6 - but it has not been added. I tried to add it(php+css) manually by downloading from github to default templates folder and using it in shortcodes - but it encountered many errors. class names , variables an so on was not defined.

**Comment by winkm89** [comment]
Hi, 
The new template is part of the next major version. If you like, you can try the beta version https://github.com/winkm89/teachPress/releases/tag/8.0beta
