### ISSUE TITLE
multiple tags as filter And/OR in search and build categories

### ISSUE THREAD

**Issue by gitbitpi** [winkm89/teachPress#165]
Hi Michael,
thanks for this awesome plugin!

Is it possible to combine multiple tags while the user filters (because in the dropdown it is only possible to choose one tag) on a search page or/and 
is it possible to use a search combining words with "And" /"OR" /"NOT" in the search field. Sorry , i couldn't find ist in the documentation. 
[
![grafik](https://user-images.githubusercontent.com/58726014/115873465-41e19900-a443-11eb-81a9-044904780e40.png)
](url)

And when i  like to have several pages with categorized literatur (Kat A (= tag no 5), Kat B (= tag no 6), Kat C (= tag no 7)) and tags (1, 2 ,3, 4) is the easyiest way to build a page with the "Kat A" to use something like: 
`[tpsearch tag=5 exclude_tags= 6, 7 ]`

Last, is there a way to make a small donation to your work (paypal or some thing)?
thanks very much for your help in advance
Pi

**Comment by winkm89** [comment]
Hi,

> Is it possible to combine multiple tags while the user filters (because in the dropdown it is only possible to choose one tag) on a search page or/and
Currently not. But that's one of the things that I want to change. The plugin core supports it already, it's just a presentation problem. 

> is it possible to use a search combining words with "And" /"OR" /"NOT" in the search field. Sorry , i couldn't find ist in the documentation.
The search field is just a full text search over some publication fields. So, operators doesn't work.

> And when i like to have several pages with categorized literatur (Kat A (= tag no 5), Kat B (= tag no 6), Kat C (= tag no 7)) and tags (1, 2 ,3, 4) is the easyiest way to build a page with the "Kat A" to use something like: [tpsearch tag=5 exclude_tags= 6, 7 ]
Yes, I think using the tag parameter should be the easiest way for that.

> Last, is there a way to make a small donation to your work (paypal or some thing)?
Doesn't exist. But that is on purpose. ;)

**Comment by gitbitpi** [comment]
Thanks Michael,
for your quick answer, so i will wait for the next release with the tags ... and your donation button ;)
Pi
