### ISSUE TITLE
Translation mistake (french version) "See all" search results translate to "Tout voir" not "Tout voire"

### ISSUE THREAD

**Issue by ThomasF63** [winkm89/teachPress#166]
Hi all,

We are using teachpress for our website and our users have noticed a translation mistake (french mistake).
When running a search, below the tp search input and the navigation arrows, the text of your plugin displays "Tout voire".
The correct french translation of what I guess has been "See all" must be "Tout voir". Without the e.
I know... french is confusing.
Could you please try to fix this little mistake in your next update, please?
All of the french WordPress sites using your plugin will definitely appreciate it!
Unfortunately, I am not good enough in web development to apply a change myself.

Best regards,

Thomas

**Comment by winkm89** [comment]
Hi Thomas,
I've received a bigger translation update today, which also changes this translation to: _Afficher tous_
I hope that's also correct. My french is rather rudimentary . :) 
The new files are includes into teachpress 7.1.6, which is available over WordPress.

**Comment by ThomasF63** [comment]
Hi Michael,
Brilliant! Thank you for this.
Take care,
Thomas


*Thomas Fungenzi*
*Agriculture engineer and Soil scientist*
Personal website: thomasfungenzi.com* <http://thomasfungenzi.com>*
Vice-president of the Association Française pour l'Etude du Sol
<https://www.afes.fr/> (AFES)
Extra-curricular project: alcheringa.fr - An adventure through Australian
farms
