### ISSUE TITLE
author_name style "short"

### ISSUE THREAD

**Issue by ruthalivingstone** [winkm89/teachPress#171]
Is it possible to use initials for first names instead of full names? The current author_name="initials" returns "van der Vaart, Ludwig C" but for ~100 author papers that gets really clunky. Would be good if we had author_name="short" returning something like "L. C. van der Vaart".

**Comment by winkm89** [comment]
I've added **author_name="short"** as a new option, which returns in the example "van der Vaart L C". In combination with  **author_separator=","** this is the same style, which is for example used on [PubMed](https://pubmed.ncbi.nlm.nih.gov/trending/)

**Comment by ruthalivingstone** [comment]
That's perfect! Thank you very much
