### ISSUE TITLE
Customize filter by author

### ISSUE THREAD

**Issue by manuelcanonad** [winkm89/teachPress#173]
How can I customize the fields of the filter? I want to filter by some authors, but not all of them.

Thanks for the help and forgive my english

**Comment by winkm89** [comment]
Hi,
You can set a list of the authors you want to show in this filter over the parameter **show_in_author_filter**. An Example:
`[tpcloud show_in_author_filter="1,3,7,11"]`
1,3,5,7,11 are the IDs of the authors. You can find this IDs in the authors section in the backend.

**Comment by manuelcanonad** [comment]
It works!

Thank you for your response.
