### ISSUE TITLE
How does the plugin manages duplicated publications

### ISSUE THREAD

**Issue by jdelgadoesteban** [winkm89/teachPress#178]
Hello, we have been testing the plugin for a few months while developing our new site is we really like it. Publications to the site are coming from Elsevier Pure via Bibtex, we will be uploading updated files every 6 months so we were wondering how doe the plugin react if in the newly uploaded file there is a publication that has already been imported.

**Comment by winkm89** [comment]
There is an option under "Settings->teachPress-->Publications" called "Update existing publications". This adds an "Update existing publications" entry to the import options. If you activate that, the plugin checks the bibtex key of each importing entry and overwrites existing publications, which helps to prevent duplicated entries.

**Comment by jdelgadoesteban** [comment]
Thanks for confirming, we have tried the feature an dit works well
