### ISSUE TITLE
Multiple titles of imported publications display texquote in the title

### ISSUE THREAD

**Issue by jdelgadoesteban** [winkm89/teachPress#179]
For example:

Coronavirus is a textquoteleftsliding doorstextquoteright moment. What we do now could change Earthtextquoterights trajectory, misc, 2020 (as author)

Is there any way of avoiding this?

Many thanks!

**Comment by winkm89** [comment]
Thank you for the data! I think the problem is that Bibtex special characters \textquoteright \textendash were just not recognized. This will be fixed with the next update.

**Comment by jdelgadoesteban** [comment]
Michael, that would be great!

Kind Regards

Javier
