### ISSUE TITLE
Cannot remove bookmarks again

### ISSUE THREAD

**Issue by IlseO76** [winkm89/teachPress#181]
Hi Michael, once I have selected a bookmark and saved the publication with that bookmark, I seem no longer able to remove it again; The bookmark checkbox in question cannot be unselected, not even if I log in as the user that this bookmark is connected to. Any idea what may cause that problem?

**Comment by winkm89** [comment]
Removing bookmarks should now working with v8.1. I also updated the UI for bookmarks a bit.
