### ISSUE TITLE
Feature request: ability to display publication links with an anchor text instead of as a (sometimes long) URL

### ISSUE THREAD

**Issue by IlseO76** [winkm89/teachPress#182]

**Comment by winkm89** [comment]
It's a bit hidden in the description of the URL field, but I think it's already working: Insert the title/text of the URL or file behind the URL and separate it by a comma and a space. Example:

https://en.wikipedia.org/wiki/Kingdom_of_England, This is England

Result:

![image](https://user-images.githubusercontent.com/9537674/136855029-3b25589d-1fe9-4a52-bd51-0a514f06852f.png)
