### ISSUE TITLE
Request several tgid from the teachpress page URL

### ISSUE THREAD

**Issue by plaste** [winkm89/teachPress#191]
Hello,
I am trying to request several tgid at a time, using URL parameters.

This URL should request the 2 tgids : 7729 and 4021 : 
https://mydomain.tld/publications/?tgid=7729,4021&yr=&type=&usr=&auth=#tppubs

But, only the publications taged with the first one are displayed on the page.

If I generate a link like the following ones (with brackets), this doesn’t work either :
.../publications/?tgid=(7729,4021)&yr=&type=&usr=&auth=#tppubs
or
.../publications/?tgid=[7729,4021]&yr=&type=&usr=&auth=#tppubs

Here is a live exemple : 
https://ibmc.cnrs.fr/publications/?tgid=7729,4021&yr=&type=&usr=&auth=#tppubs

Please apologies if this is not an issue and Teachpress can't request 2 tgids from the URL at this time. 
Then it would be a feature request... Maybe we can help to implement this, in that case ?

**Comment by winkm89** [comment]
Hi, this should now work with v. 8.1.3 without brackets. The bad news is that the tag filter (tag cloud and select) can't handle that currently. But multiple selects are  a bigger task to do. :)
