### ISSUE TITLE
Publications no longer working

### ISSUE THREAD

**Issue by mere13** [winkm89/teachPress#194]
Hi there. I recently updated my site and plugins and the existing publication list I had created has disappeared. Now, when I try to add new publications, they don't save and the 'your publications' window remains empty. Any help would be much appreciated. Thanks in advance!

**Comment by winkm89** [comment]
Hi,

Firstly: Please change to following flag in your **wp-config.php**:

```php
define( 'WP_DEBUG', false );
```

to this:

```php
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_DISPLAY', true );
define( 'SCRIPT_DEBUG', true );
```

This should show you the real error messages which are not visible by default.

**Comment by winkm89** [comment]
And a question: Do you know which version of teachPress you had installed before the update?

**Comment by mere13** [comment]
Thanks Michael. This is the error code: WordPress database error: [Unknown column 'p.issue' in 'field list']
SELECT DISTINCT p.pub_id, p.title, p.type, p.bibtex, p.author, p.editor, p.date, DATE_FORMAT(p.date, '%Y') AS year, p.urldate, p.isbn, p.url, p.booktitle, p.issuetitle, p.journal, p.issue, p.volume, p.number, p.pages, p.publisher, p.address, p.edition, p.chapter, p.institution, p.organization, p.school, p.series, p.crossref, p.abstract, p.howpublished, p.key, p.techtype, p.note, p.is_isbn, p.image_url, p.image_target, p.image_ext, p.doi, p.rel_page, p.status, p.added, p.modified, p.import_id FROM wp_n73ein_teachpress_pub p ORDER BY p.date DESC LIMIT 0,50

**Comment by mere13** [comment]
And, actually, I just "rolled back" the plugin to the previous version and then re-updated it, which prompted a database update. That fixed the problem. I have a publication list again. Thank you for getting back with me.
