### ISSUE TITLE
Warning: Undefined array key after upgrade to php 8.1

### ISSUE THREAD

**Issue by riggas-ionio** [winkm89/teachPress#201]
After a server upgrade to php 8.1 a page using wordpress shortcode `[tpcloud entries_per_page="100" style="none" template="tp_template_2021"]` give warning:

```
Warning: Undefined array key "" in /wp-content/plugins/teachpress/core/shortcodes.php on line 407
Warning: Undefined array key "" in /wp-content/plugins/teachpress/core/shortcodes.php on line 407
Warning: Undefined array key "" in /wp-content/plugins/teachpress/core/shortcodes.php on line 407
Warning: Undefined array key "" in /wp-content/plugins/teachpress/core/shortcodes.php on line 407
```

A proposed fix, which works, is editing [teachPress](https://github.com/winkm89/teachPress)/[core](https://github.com/winkm89/teachPress/tree/master/core)/shortcodes.php and adding at line 407:

```
            if ( empty($key) ) {
                continue;
            }
```

Hope this helps, Dimitrios

**Comment by winkm89** [comment]
Hi Dimitrios,
Thank you for reporting this bug! Should be fixed with 8.1.7.
