### ISSUE TITLE
[tpcloud user=?] User id can be neitjer found in teachpress nor wordpress

### ISSUE THREAD

**Issue by nise** [winkm89/teachPress#202]
Wordpress and teachpress makes it hard to identify one's own user id. However, if I want to restrict the publication to one user I need to know the user id, e.g. [tpcloud user=1]. Even on a freshly installed Wordpress user id  1 is not the admin who installed it.

So, how can I get to know my user id if I have no access to the code? Where exactly is the user id shown in teachpress?

**Comment by winkm89** [comment]
Hi, a quick fix is to install a plugin, which displays the user IDs in the WordPress' user section: https://wordpress.org/plugins/show-user-id/
But you're right, it's really not that easy to find.

**Comment by nise** [comment]
You could provide the user id on the page of one's own publications.

**Comment by fabricebg** [comment]
Or, the shortcode could accept a username as id, i.e. `[tpcloud user=wordpress_user_name]` .

**Comment by winkm89** [comment]
The shortcodes tpcloud, tpsearch, tplist accept also the user name since teachPress 9.0.0. This should help to solve the issue.
