### ISSUE TITLE
pulldown menu formatting incorrectly

### ISSUE THREAD

**Issue by bocajpj** [winkm89/teachPress#203]
Hello,

I'm moving from an older WP theme to a new one, and can't make the tag pulldown menu format correctly.

Here's the old one:
![image](https://user-images.githubusercontent.com/116893705/198611958-f57f1653-75b3-4e73-bdbf-c2c9440358ac.png)

Here's the new one:
![image](https://user-images.githubusercontent.com/116893705/198612474-02f8a4df-57c4-4e2e-899a-505466f34ca9.png)

I can't find any other pulldown errors listed here or at WP support, so am posting here. I'm grateful for your help.

John

**Comment by winkm89** [comment]
Hi, it's more a "problem" with your new WP theme. You need to add some CSS rules which helps to overwrite the theme defaults for select fields. The select fields for teachpress has an own CSS selector which helps you to write it:

```CSS
.teachpress_filter select { 
/* Write the rules here */ 
}
```
Unfortunately, I can't help you more precisely, I would need a link to your site for that.

**Comment by bocajpj** [comment]
Hi Michael, thanks for your help. I'm not sure where to make the changes you suggest. I looked for the CSS selector but couldn't find it. Can you direct me to it. Are there any examples of rules writing you can also point me to? 
Here are the site links:
- https://www.photocurator.me/list/ (this is the old site, working as desired)
- https://staging.photocurator.me/press/ (this is the new site, not working as desired)
Thanks again,
John

**Comment by fabricebg** [comment]
John, you can solve your problem with the following CSS code:

```
.teachpress_filter select { 
  width: initial;
  display: initial;
  appearance: revert;
}
```

You can copy-paste this code into your own theme (Mies in your case), by Customizing your theme, and selecting the "Addtional CSS" option. See [here](https://www.wpbeginner.com/plugins/how-to-easily-add-custom-css-to-your-wordpress-site/) for the procedure.

Fabrice
