### ISSUE TITLE
Importing special characters from bibtex

### ISSUE THREAD

**Issue by davidmallasen** [winkm89/teachPress#212]
Hello, 

When importing some special characters from bibtex, there seems to be some issue where the utf-8 corresponding characters are not rendered properly (or not rendered at all). In particular:
~~~
{\~n} should be ñ
{\'\i} should be í
{\'u} should be ú
{\`e} should be è
~~~
Thank you.
David

**Comment by qrossy** [comment]
Hello,

How to avoid this "L'utilisation..." to be import as "Lútilisation..." from bibtex ?

Thank you very much,
Quentin

**Comment by davidmallasen** [comment]
With the latest 9.0.0 version the `{\~n} should be ñ` was fixed, but not:
~~~
{\'e} should be é
{\'a} should be á
{\'\i} should be í
...
~~~
These are the bibtex formats as exported by Google Scholar
