### ISSUE TITLE
Feature suggestion: tplist by tag name

### ISSUE THREAD

**Issue by tom-nagels** [winkm89/teachPress#219]
With only a few code additions tplist shortcode works fine with tag names in stead of id's which works far more intuitively for those administering content.

Modified files attached for you to review

[tplist-filter-by-tag-name.zip](https://github.com/winkm89/teachPress/files/11071733/tplist-filter-by-tag-name.zip)

**Comment by winkm89** [comment]
Hi Tom,
Thanks for the additions! I've merged it with the main branch.
