### ISSUE TITLE
tpcourseinfo and tpcourselist rendering bugs

### ISSUE THREAD

**Issue by MarzioVallero** [winkm89/teachPress#223]
Hello everyone.
I am trying to set up a simple courses page for the members of my research group.
I added the courses from the WP dashboard, however the information is rendered in a weird way.
The "tpcourselist" produces a list of course names, without any of the additional information provided in the metadata of each course.
The "tpcourseinfo" renders the word "Date(s)" on the top left of the box and does not display the course name.
As a last request, would it be possible for custom course meta fields to be ignored during rendering if they are left empty?
I attached a screenshot of the rendering of "tpcourseinfo" with anonymised information: the BW boxes are where text from the various fields is positioned.

![capture_tc_bug](https://user-images.githubusercontent.com/73691795/230631435-6bd70f37-7f69-47d0-9f7e-0e2559c44d87.PNG)

**Comment by winkm89** [comment]
Unfortunately, this will not be fixed because the course management was removed from the plugin with teachPress 9.0.
