### ISSUE TITLE
I can not manage articles

### ISSUE THREAD

**Issue by glgrazi** [winkm89/teachPress#228]
After updating to version 9, I am no longer able to manage my articles.
This is the error that is reported by the plugin 

Custom meta data

Fatal error: Uncaught Error: Class 'TP_Enrollments' not found in /home/customer/www/chirurgiadelfegato.it/public_html/wp-content/plugins/teachpress/core/admin.php:104 Stack trace: #0 /home/customer/www/chirurgiadelfegato.it/public_html/wp-content/plugins/teachpress/core/admin.php(426): TP_Admin::get_checkbox_field('tp_meta_pub_Arg...', 'Argomento artic...', '{Epatocarcinoma...', false, false) #1 /home/customer/www/chirurgiadelfegato.it/public_html/wp-content/plugins/teachpress/admin/add-publication.php(179): TP_Admin::display_meta_data(Array, Array) #2 /home/customer/www/chirurgiadelfegato.it/public_html/wp-includes/class-wp-hook.php(308): tp_add_publication_page('') #3 /home/customer/www/chirurgiadelfegato.it/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #4 /home/customer/www/chirurgiadelfegato.it/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 /home/customer/www/chirurgiadelfegato.it/public_html/wp-admin/admin.php(259): do_action('publicazioni_pa...') #6 {main} in /home/customer/www/chirurgiadelfegato.it/public_html/wp-content/plugins/teachpress/core/admin.php on line 104

**Comment by winkm89** [comment]
Should be fixed with v9.0.1

**Comment by glgrazi** [comment]
Thanks for the reply.
Do you know when version 9.01 will be released?
I ask only to plan the activities of the site.
Need more details about the error?
I can't edit the tags of the articles and I can't always import them.
Thank you

Gian Luca

**Comment by winkm89** [comment]
It's already released. ;-) 

On [Github](https://github.com/winkm89/teachPress/releases/tag/9.0.1) and also on [WordPress.org](https://wordpress.org/plugins/teachpress/)
