### ISSUE TITLE
hide_tags and show_tags_as="pulldown" are not working [tpcloud]

### ISSUE THREAD

**Issue by hilbricm** [winkm89/teachPress#230]
Hi, the combination hide_tags and show_tags_as="cloud is working fine. The tag-cloud is reduced by the hidden tags.
If I change to show_tags_as="pulldown", all tags are displayed in the pull-down (no tags are hidden).

Thank you

**Comment by lazikchr** [comment]
I have the same problem. The tags are hidden in the publications themselves. But they are still present in the tag pull down menu.

**Comment by hilbricm** [comment]
[tpsearch] supports show_tags_as="cloud, but hide_tags is not working (pulldown and cloud).
