### ISSUE TITLE
Problem with including wp-load.php

### ISSUE THREAD

**Issue by eriktews** [winkm89/teachPress#35]
Hi

There seems to be a problem in the export feature in export.php line 9:

https://github.com/winkm89/teachPress/blob/master/export.php#L9

Here, wp-load.php is included, which might be at a totally different location depending on where wordpress and the plugin is installed, resulting a 500 internal server error.

The problem seems to be known in general, however I currently don't know what would be the best solution for teachPress:

https://wordpress.stackexchange.com/questions/26254/how-to-include-wp-load-php-from-any-location

**Comment by winkm89** [comment]
Hi,

The wp-load include is an really old hack I use for the export, feed and some ajax functions. Should work for 98% of all WordPress installations but leads to problems, if someone changes the default file structure. So, you're right, this needs a better solution. I will try to find one.

**Comment by winkm89** [comment]
Ok, exports and feeds run now over WordPress. So, in this cases the wp-load.php hack is no longer needed. New urls:
**RSS:** 
http://[yourwp.com]/feed=tp_pub_rss

**BibTeX:**
http://[yourwp.com]/feed=tp_pub_bibtex

**Export:**
http://[yourwp.com]/feed=tp_export?type=pub?format=[txt|bib|rtf]

**Comment by winkm89** [comment]
I have removed the wp-load.php hacks from the source code now and switched everything to the WordPress AJAX interface. I hope it works :)
