### ISSUE TITLE
delete publication fails

### ISSUE THREAD

**Issue by bodobalazs** [winkm89/teachPress#45]
in publication delete 
the 
DELETE FROM " . TEACHPRESS_PUB . " WHERE `pub_id` = '$checkbox[$i]'
query fails with 
"Cannot delete or update a parent row: a foreign key constraint fails" error since 
TEACHPRESS_PUB_META
still uses pub_id as foreign key
please add 
$wpdb->query( "DELETE FROM " . TEACHPRESS_PUB_META . " WHERE `pub_id` = '$checkbox[$i]'" );
to
public static function delete_publications
before $wpdb->query( "DELETE FROM " . TEACHPRESS_PUB . " WHERE `pub_id` = '$checkbox[$i]'" );

**Comment by winkm89** [comment]
Many thanks for the bug report. This will be fixed today with the next release.
