### ISSUE TITLE
Error for publication list

### ISSUE THREAD

**Issue by twallbaum** [winkm89/teachPress#49]
When integrating the [tplist] shortcut to a page i'm receiving the error:

Fatal error: Declaration of tp_template_2016::get_body() must be compatible with that of tp_publication_template::get_body()

I'm using teachPress v 6.0 and WP v4.7.1. Publicationlist has been important using Bibtex

**Comment by winkm89** [comment]
Hi,
Many thanks for the report. Unfortunately, I can't reproduce that with WP v4.7.1 under PHP 5.6 or PHP 7. But I have an idea, what leads to this error. Could you test the following fix?: https://github.com/winkm89/teachPress/commit/94d639ec4f19b37349612f9151363b8f4675c50d

**Comment by twallbaum** [comment]
Hi,
works perfectly fine now! Thanks

**Comment by winkm89** [comment]
That's great. Thanks for testing!
