### ISSUE TITLE
How can I import bibtex file with url image and tags information?

### ISSUE THREAD

**Issue by husk00** [winkm89/teachPress#53]
Hi,
thanks for this amazing plugin.
There is a way to use bibtex format to include also tags and image url for publication?

salut!

**Comment by winkm89** [comment]
Hi,
Sorry for the late answer! Tags should be automatically imported if they are defined as "keywords" or "tags" in the bibtex code. Image urls can also imported, if they are defined as "image_url". But the plugin doesn't import the image itself.

An Example:

`@article{Abrams2016,
title = {Test},
author = {A. A. Abrams},
url = {http://gammap.cs.unc.edu/BSwarm/Bswarm.pdf, PDF
http://gammap.cs.unc.edu/BSwarm/Bswarm.mp4, Video},
year = {2016},
date = {2016-12-28},
keywords = {Agile BI, Demo},
pubstate = {published},
image_url = {https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Ceres_RC3_with_bright_spots.jpg/279px-Ceres_RC3_with_bright_spots.jpg},
tppubtype = {article},
abstract = {This is an abstact}
}`
