### ISSUE TITLE
Extra space, year in bibliographic entries

### ISSUE THREAD

**Issue by howardjp** [winkm89/teachPress#54]
I love your software and use it to manage my bibliography on my website.  There's a long outstanding bug where the year is given twice in the default compact form.  You can see it in action here:

  https://jameshoward.us/writing/public-economics/

(This previously referenced an extra space, but that was easy to fix, so I just submitted a pull request for that.  Somehow, this is more interesting a problem.)

**Comment by winkm89** [comment]
Hi,

Thanks for the pull request! I know the bug with the year in the 1-line-style. I belive this problem exists since the first public version of the plugin 8 years ago. ;) It's a little bit nasty to fix, but I'm working on it.

**Comment by howardjp** [comment]
Actually, I have an alternative solution.  For things like talks, conferences, or other types that have well-defined specific dates (as opposed to just years), printing the full date the second time might be nice.  This may also be difficult to implement.
