### ISSUE TITLE
filtering [tplist] with tags

### ISSUE THREAD

**Issue by littledude** [winkm89/teachPress#57]
Hi I'm having difficulty to filter tplist with tags. Is the shortcode correct [tplist tag="my-tag"]? If yes, what could be the reason the list doesn't show up? Thanks!

**Comment by winkm89** [comment]
Hi, do you use tag with the tag name [tplist tag="my-tag"] or the tag id [tplist tag="52"]? Because the tag name will not work ;)

**Comment by littledude** [comment]
Hi Michael 

Thanks for your fast response. I used the name, which was why it didn't work. I was pulling my hair and almost wanted to give up. You are really a life-saver!

I really appreciate you developed this useful plugin. I have three suggestions:

For the Github wiki, it will be nice to see an example of using each parameter. I am not really a programmer and examples are super helpful. 

For the tplist, based on the APA style, tittle should be before author. Can you adjust the default template in the future? For now I have to use JavaScript to change the order.

For the tpcloud, the author filter is not helpful because it often has more than one author. Instead of using tag clouds, can you convert the tags as one of the filters? 

Thanks again for your help!
Kevin

**Comment by winkm89** [comment]
Hi Kevin,

1) I'm trying to add some more examples ;)
2) teachPress doesn't really use the APA style. But since teachPress 6.0 the templates can be modified simplier, users can add own or I can add more additional default templates. :) For a title and author switch, the following lines must be modified: https://github.com/winkm89/teachPress/blob/master/templates/tp_template_2016.php#L85 and L86
3) You can already switch between a cloud or a pulldown filter. For the pulldown: [tpcloud show_tags_as="pulldown"] The author filter shows normally all authors. But I think it's a problem which is related to #58

**Comment by littledude** [comment]
Hi Michael,
Thanks for letting me know that TeachPress doesn't use the APA style. However, my stakeholder just confirmed that that's his preference. If the template can be modified through the code, how I can reformat it to look like the following APA structure:
Freedland, K.E., Mohr, D.C., Schwartz, J.E., Davidson, K.W. (2011) 
Usual and Unusual Care: Existing Practice Control Groups In Randomized Controlled Trials of Behavioral Interventions, 
Psychosomatic Medicine, 73, 323-335. PMID: 21536837
I am sorry to bother you but I am not familiar with PHP and don't want to make the issue worse. 

If you can design a APA template, that'll be awesome because that's one of the most popular citation formats and I am sure your plugin will help more users in academic field. 

As for the author name output, do you think it'll be helpful if we can remove the format restriction when entering the data? or is this related to the character set? or Can adding additional Javascdript/jQuery help? For your information, the period after the abbreviation will be omitted for certain reason. Also, ";" will be added if I use more than one "and" to connect multiple names. Furthermore, it seems that it has a hard time to recognize abbreviations as first name, for example, K.E. or D.C..
I certainly know this can be a lot of work. I just want to thank you for being willing to improve your product by sacrificing your personal time.
Thanks!Kevin
