### ISSUE TITLE
incorrect author output

### ISSUE THREAD

**Issue by littledude** [winkm89/teachPress#58]
Hello again - I just noticed that the author output is incorrect. For example, I entered the following:

Mohr DC, Siddique J, Ho J, Duffecy J, Jin L, Fokuo JK.

While it looks the same in the database, it shows the below output on the page:

Mohr DC Siddique J, Ho Duffecy Jin Fokuo JK. J J L

It seems that it was forced to reformatted. Is there a way to disable the format? 

Thanks!

**Comment by winkm89** [comment]
It's a little problem with the input. The author string must have the following format: 
`fistname1 lastname1 and fistname2 lastname2 and ...` So you need at least " and " as a separator between the authors.

**Comment by littledude** [comment]
Hi Michael 

I did do that but it turns "and" to ";". However I need it to be "," (comma). Is there a way to make it work the way I want? I tried to use jQuery to change

**Comment by littledude** [comment]
I tried to use jQuery to change the text but it only changed the first ";" for certain reason.

Thanks for your help 
Kevin

**Comment by winkm89** [comment]
I really recommend to use " and " as separator, because the plugin expects this for some functions. The ";" in the frontend is currently [hard-coded](https://github.com/winkm89/teachPress/blob/master/core/class-bibtex.php#L424) (the ";" after $all_authors). But I think I can add an option to override that.

**Comment by littledude** [comment]
Thank you so much, Michael! 

I think I can persuade the stakeholder to use "and". As long as you can find a way to overwrite ";", that will be the last big hurdle I need to solve. 

Please keep me posted.

Thanks again!
Kevin

**Comment by winkm89** [comment]
I've added a new version (6.0.4 beta) to [releases ](https://github.com/winkm89/teachPress/releases), which supports custom author/editor separators:
An example:
`[tplist author_separator=","]` 
The same is also possible for editors:
`[tplist editor_separator=","]`
