### ISSUE TITLE
Please add Patent type

### ISSUE THREAD

**Issue by crezol** [winkm89/teachPress#59]
Thank you for awesome plugin for managing publication.
I have hundreds of patents to list up, but teachPress can't support patents bibtex type. 

So, here is the question.
1. Is there any way to add bibtex supported type?
2. Or, could you add the bibtex type on teachPress to handle this?

The patent bibtex type information is
http://www.see-out.com/sandramau/bibpat.html

and sample is 

```
@Patent{EHLINGER:2006:biblatex,
 author = {EHLINGER, JR., Philip Charles},
 title = {Device for the treatment of hiccups},
 year = {2006},
 month = {06},
 day = {13},
 number = {US 7062320},
 type = {Patent},
 version = {},
 location = {US},
 url = {http://www.patentlens.net/patentlens/patent/US_7062320/},
 filing_num = {10684114},
 yearfiled = {2003},
 monthfiled = {10},
 dayfiled = {14},
 pat_refs = {US 408607 A (Aug, 1889) Flint 607/134; US 4210141 A (Jul, 1980) Brockman et al. 604/78},
 IPC_class = {A61N 1/04},
 US_class = {607  2},
 abstract = {A device for the treatment of hiccups, and more specifically, to a method and apparatus for the treatment of hiccups involving galvanic stimulation of the Superficial Phrenetic and Vagus nerves using an electric current.}
}
```

Thank you again!

**Comment by winkm89** [comment]
Hi,

Adding new publication types is easy (just one line of code :) ). The difficult part are the data fields. The example here uses some fields, which are not mentioned in the Biblatex documentation:

```
A patent or patent request. The number or record token is given in the number
field. Use the type field to specify the type and the location field to indicate the
scope of the patent, if different from the scope implied by the type. Note that the
location field is treated as a key list with this entry type, see § 2.2.1 for details.

Required fields: author, title, number, year/date
Optional fields: holder, subtitle, titleaddon, type, version,
location, note, date, month, year, addendum, pubstate, doi, eprint,
eprintclass, eprinttype, url, urldate
```

So, the question is: Which fields do you need? ;)

**Comment by crezol** [comment]
Oh, there was the description of patent type on Biblatex documentation!.

> + author, title, number, year/date (Required fields)
> + type, location, filing_num(or just use addendum field), abstract(maybe, not essential)

I think, these fields are enough to show patent. 
Is it possible to handle this? 

Thank you winkm89.

**Comment by winkm89** [comment]
I've added a new version (6.0.4 beta) to [releases ](https://github.com/winkm89/teachPress/releases), which supports the patent type. Some notes to the fields: 
- The following fields are available: author, title, number, year/date, type, abstract, address, note
- I'm using "address" instead of "location" (teachPress switches that back to "location" in BibTeX outputs)
- addendum is in teachPress similar to note

**Comment by crezol** [comment]
Thank you winkm89!.

**Comment by crezol** [comment]
I tested the new version (6.0.4 beta), and patent looks work well.
Unfortunately, there is unexpected bug about tp course in 6.0.4 beta.
In the new version, I can't edit and delete exist courses with "no permission to access this page" message.
I tried to uninstall the DB and clean install, but it doesn't help to solve.
Sorry for bothering you, but please check this problem.

Thanks!

**Comment by winkm89** [comment]
Sorry, I can't reproduce that. It works for me. 6.0.4 includes no changes in the course system. So, I'm a bit confused. Which URL is showing in your browser, when you see the message?

**Comment by crezol** [comment]
Ah, sorry, It is solved.
When I did install 6.0.4 beta by plugin import in wordpress with .zip file upload, then the issue was happened.
I just replace the plugin files to beta release files in same folder name, then it works fine.
Thank you for your support and great plugin :)
