### ISSUE TITLE
Update overwrites custom templates

### ISSUE THREAD

**Issue by matteoacrossi** [winkm89/teachPress#60]
Wordpress plugin update overwrites the teachpress plugin folder and thus any custom template that was placed in the templates subfolder gets overwritten. I see that it is possible to [move the template folder away](https://github.com/winkm89/teachPress/wiki/FAQ#how-can-i-change-the-directory-of-teachpress-templates) from the plugin folder, but then the changes that one has to make to `teachpress.php` are lost after an update too, so eventually user intervention is needed to fix this at every update.

I think that a way to solve this problem must be devised.

**Comment by winkm89** [comment]
Hi,

I know that this is a problem. As I [wrote in the FAQ](https://github.com/winkm89/teachPress/wiki/FAQ#how-can-i-change-the-directory-of-teachpress-templates) (I updated this point a bit) you can define the needed constants also in the `wp-config.php` file. But I can't directly extract the specific basic paths via `wp_upload_dir()` here, so the user have to write the paths by itself in the file.

Any smarter ideas to fix it are welcome!

***

If someone want's to read out the paths:
```php
// Code for read out the basic paths of the WordPress installation:
$tp_upload_dir = wp_upload_dir();
echo 'basedir: ' . $tp_upload_dir['basedir'];
echo 'baseurl: ' . $tp_upload_dir['baseurl']; 
```

**Comment by teored90** [comment]
Mhmh I don't know the structure of WP, but isn't there a way for the plugin to save files that are preserved between updates? 
Otherwise, adding a field in the plugin settings page (that I guess is stored in the db and thus survives the update process) with the path to the template dir could be an option.
