### ISSUE TITLE
Option to mark (and label) publications as “open access”

### ISSUE THREAD

**Issue by einemarc** [winkm89/teachPress#61]
Hi.

Thank you for developing this Wordpress plugin and continuously improving it.
I manage a website for which I use teachPress for displaying publication lists, which works great. As open access publishing is on the rise, but not close of being the usual case in most academic disciplines, I end up with lists containing closed as well as open publications.

Therefore, it would be nice to be able to mark open access publications with a simple checkbox, and have a corresponding (green colored) label "Open" or "Open Acess" displayed next to the entry. That's basically very similar to the current feature with which forthcoming publications can be marked as such, and maybe a very simple modification!? As far as I'm concerned, I would find it very useful.

If it's not possible to add the feature, I'd love to know how difficult it would be to add this myself. (Unfortunately, I am not familiar enough with the teachPress code to just quickly code this myself and submit this change, yet.)

Best regards!

**Comment by winkm89** [comment]
Hi,
Adding the data field is quite simple (can be done over teachPress' meta data system). But it's hard to show it, because I never finished the system for using meta data for publications in the frontent. I will think about a solution for that.

**Comment by einemarc** [comment]
Thank you for adding the support. I had a look at the changes in the database.php.

Am I right that I would now only need to add a meta data field (and at least one element) in the teachPress settings as well as make changes to the templates.php and tp_template_2016.php (using this template as an example)?
I am not an expert in PHP. But if you give me a hint and I know where to look, I might be able to get my labels done by tinkering with the code.

**Comment by winkm89** [comment]
I've written a small guide for that: https://github.com/winkm89/teachPress/wiki/Create-custom-labels-for-publication-lists
I hope, that this helps ;)

**Comment by einemarc** [comment]
It does, indeed. It is a very nice feature. Thanks a lot!
