### ISSUE TITLE
deleting publications fails again in WP 4.8 

### ISSUE THREAD

**Issue by nise** [winkm89/teachPress#63]
I don't know what kind of logs I could provide you, but whenever I try to delete a publication it appears again on the list.

**Comment by winkm89** [comment]
Hi,
I have an idea: There is in the plugin directory a file: teachpress/core/database.php Open it and search after the function `delete_publications`. Replace this function with the following version:
`
public static function delete_publications($checkbox){	
        global $wpdb;
        $wpdb->query("SET FOREIGN_KEY_CHECKS=0");
        $max = count( $checkbox );
        for( $i = 0; $i < $max; $i++ ) {
            $checkbox[$i] = intval($checkbox[$i]);
            $wpdb->query( "DELETE FROM " . TEACHPRESS_RELATION . " WHERE `pub_id` = '$checkbox[$i]'" );
            $wpdb->query( "DELETE FROM " . TEACHPRESS_REL_PUB_AUTH . " WHERE `pub_id` = $checkbox[$i]" );
            $wpdb->query( "DELETE FROM " . TEACHPRESS_USER . " WHERE `pub_id` = '$checkbox[$i]'" );
            $wpdb->query( "DELETE FROM " . TEACHPRESS_PUB_META . " WHERE `pub_id` = '$checkbox[$i]'");
            $wpdb->query( "DELETE FROM " . TEACHPRESS_PUB . " WHERE `pub_id` = '$checkbox[$i]'" );
        }
        $wpdb->query("SET FOREIGN_KEY_CHECKS=1");
    }
`
Save the file and try again deleting publications.

**Comment by nise** [comment]
That did not work. Have you been able to reproduce the bug on your system?

**Comment by nise** [comment]
Even after fixing some missing balnks and string end. No deletion.
`public static function delete_publications($checkbox){ 
    	global $wpdb; 
    	$wpdb->query("SET FOREIGN_KEY_CHECKS=0"); 
    	$max = count( $checkbox ); 
    	for( $i = 0; $i < $max; $i++ ) 
    	{ 
    		$checkbox[$i] = intval($checkbox[$i]); 
    		$wpdb->query( "DELETE FROM " . TEACHPRESS_RELATION . " WHERE pub_id= '$checkbox[$i]'" ); 
    		$wpdb->query( "DELETE FROM " . TEACHPRESS_REL_PUB_AUTH . " WHERE pub_id= '$checkbox[$i]'" ); 
    		$wpdb->query( "DELETE FROM " . TEACHPRESS_USER . " WHERE pub_id= '$checkbox[$i]'" ); 
    		$wpdb->query( "DELETE FROM " . TEACHPRESS_PUB_META . " WHERE pub_id= '$checkbox[$i]'"); 
    		$wpdb->query( "DELETE FROM " . TEACHPRESS_PUB . " WHERE pub_id= '$checkbox[$i]'" ); 
    		} 
    		$wpdb->query("SET FOREIGN_KEY_CHECKS=1"); 
    	}`

**Comment by winkm89** [comment]
No, unfortunately I can't reproduce it. It works as expected under WordPress 4.8 and PHP 5.6 or 7.0 and MySQL 5.7. 
The idea above was a test if it's a problem with the foreign key constraints of MySQL. This was the problem in prior "can't delete" bugs. 
Can you set [WP_DEBUG to true](https://codex.wordpress.org/Debugging_in_WordPress) in your wp-config.php? Hopefully this helps to become an error message...
