### ISSUE TITLE
Add workshops as a publication type

### ISSUE THREAD

**Issue by awmp1** [winkm89/teachPress#67]
I find that I am attending more and more 'workshops', which often have whitepaper or the like as output. Is it possible to add 'workshop' as a publication type in an upcoming release. I think it would basically have the same fields as a conference.

**Comment by winkm89** [comment]
Hi,
Adding new publication types is simple, so no problem here. But I'm struggling a bit with the name. What you describe sounds like more after "Workshop papers"?

**Comment by awmp1** [comment]
Personally the type from my perspective could be just be 'Workshops'
because the output varies and include things like 'white papers', 'policy
briefs', 'direction papers' etc.
