### ISSUE TITLE
ptlist wish: is it possible to let the user filter by tag?

### ISSUE THREAD

**Issue by arekusan** [winkm89/teachPress#69]
Hello,
I would be very happy if the user could not only filter by year, etc. . Is it possible to offer him the possibility to filter by tag oder to give him a full text search in the list?

Thanks a lot for your effort
Arekusan

**Comment by winkm89** [comment]
`[tplist]` has no end user filters. That's the idea of this shortcode. For a list with filters, you can use the `[tpcloud]` shortcode, for a search `[tpsearch]`
