### ISSUE TITLE
PHP error after update

### ISSUE THREAD

**Issue by jposterloh** [winkm89/teachPress#88]
Hi, 

after updating to 6.2 I got a php error 
`Parse error: syntax error, unexpected '[' in wp-content/plugins/teachpress/core/templates.php on line 475`. 
I checked it and you use a [] initialiser, which seems is not supported in our PHP version. Would you be willing to use `array()` for backwards compatibility? 

Best 
Jan-Patrick

**Comment by winkm89** [comment]
Hi Jan-Patrick,

I will fix that compatibility problem. But I strongly recommend an update of the server, because PHP versions lower than 5.4 receive no security patches since more than 3 years!
