### ISSUE TITLE
Template solid border bug

### ISSUE THREAD

**Issue by awmp1** [winkm89/teachPress#99]
I'm not sure if this is a bug but when I try to change the solid border CSS in my custom template, the changes are not reflected on the website. When I use inspector in Firefox, it seems that the tplist is still looking for the css in template_orig and not in my new template.

**Comment by winkm89** [comment]
It only works, if everything uses the same name:

```
custom_template.css
custom_template.php
```

and

`[tplist template="custom_template"]`

**Comment by awmp1** [comment]
Hi Michael,
Thanks for your reply. 
I do have all those entries the same. I’ve been digging a little further. I wonder if it is because I have teachPress as a plugin within AVADA theme. Usually when I do custom CSS I have to add !important to have it actioned. I’ve attached the inspector output from Firefox and I think that this may be the source of the problem. You can see on the right that the script is calling up both templates but its ignoring the custom template that I have specified. I’m not sure how to fix it, I’m still digging around try to understand how the custom template CSS is called within the code (I’m not super familiar with Wordpress coding).

Andrew


On 14 Apr 2018, at 6:04 am, Michael <notifications@github.com> wrote:

It only works, if everything uses the same name:

custom_template.css
custom_template.php
and

[tplist template="custom_template"]

**Comment by winkm89** [comment]
Without a picture or a link to the page it's difficult to say. In general you can see in the inspector which CSS cames from which file (blue marker) and which definition is used (red marker).
![devtools](https://user-images.githubusercontent.com/9537674/39014346-646a58fe-441a-11e8-84d9-e0d89712660b.JPG)
